### ISSUE TITLE
Build problem again

### ISSUE THREAD

**Issue by ericfong** [pegli/ti_touchdb#10]
After upgrading Xcode to 4.3.3
## and pull the submodule CouchCocoa to 

commit 54ec21e2e5b40408c46d85eb9d9594ca2933fe91
Author: Jens Alfke jens@couchbase.com
Date:   Sun Jul 1 10:09:51 2012 -0700
## 'Fixed compiler warnings from newer Clang' 

I got fews fatal errors:

ti_touchdb/mobile/ios/Classes/CouchDocumentProxy.m:12:9: fatal error: 'CouchCocoa/CouchDocument.h' file not found
# import <CouchCocoa/CouchDocument.h>

I think the compiler cannot locate the libCouchCocoa.a which is exits in 

ti_touchdb/mobile/ios/vendor/CouchCocoa/build/Release-CouchCocoa-ios-universal/libCouchCocoa.a

I am new to Xcode and python build.py build system. Can you please offer a help

Thanks
