### ISSUE TITLE
Issue with deployment on Android (Lollipop).. 

### ISSUE THREAD

**Issue by mycodeitches** [pegli/ti_touchdb#97]
Hello

I just recently started building on Titanium and also was intrigued on using couchbase and following links on using couchbase lite, I came across titouchdb.

I downloaded titouchdb using the following command given on the website. Command used is -->
gittio install com.obscure.titouchdb

Now the thing is, mine is very simple project as of now. I have a login screen, a user model and am trying to save it. This is happening perfectly fine on the IOS emulator.

But, the same on the Android emulator or Android Device (using lollipop, sdkversion 21), I am getting the following error.

[INFO] :   TiTouchDB: com.obscure.titouchdb.TitouchdbModule@34955741 loaded
[WARN] :   W/System.err: java.lang.NoSuchFieldError: no "I" field "mConnectionPtr" in class "Landroid/database/sqlite/SQLiteConnection;" or its superclasses
[ERROR] :  TDCollateJSON: Can't find SQLiteConnection.mConnectionPtr
[WARN] :   W/System.err: 	at com.couchbase.touchdb.TDCollateJSON.nativeRegisterCustomCollators(Native Method)
[WARN] :   W/System.err: 	at com.couchbase.touchdb.TDCollateJSON.registerCustomCollators(TDCollateJSON.java:11)
[WARN] :   W/System.err: 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
[WARN] :   W/System.err: 	at com.couchbase.lite.Database.open(Database.java:911)
[WARN] :   W/System.err: 	at com.couchbase.lite.Manager.getDatabase(Manager.java:227)
[WARN] :   W/System.err: 	at com.obscure.titouchdb.DatabaseManagerProxy.getCachedDatabaseNamed(DatabaseManagerProxy.java:71)
[WARN] :   W/System.err: 	at com.obscure.titouchdb.DatabaseManagerProxy.getDatabase(DatabaseManagerProxy.java:89)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:299)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:135)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)

I am not sure on how to progress as the project that I am working on has an initial release on android and a subsequent one on IOS... But if the android version does not work, then we might not go ahead with the IOS version.

Details of the dev environment and setup are:
Operating System
  Name                        = Mac OS X
  Version                     = 10.10.1
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 17179869184
Node.js
  Node.js Version             = 0.10.29
  npm Version                 = 1.4.21
Titanium CLI
  CLI Version                 = 3.4.1
Titanium SDK
  SDK Version                 = 3.5.0.GA
  Target Platform             = android
[INFO] :   Found Titanium plugin id=ti.alloy version=1.0 
[INFO] :   Deploy type: test
[INFO] :   Building for target: device
[INFO] :   Building for device: ZX1G522HPC
[INFO] :   Targeting Android SDK: 21

**Comment by pegli** [comment]
Up to this point, I've been building the Android version of the module with SDK 15 and testing on a 4.4.4 emulator.  I tested the latest module on a 5.0 emulator and didn't see the error you are reporting.  Can you try downloading the prerelease version 1.2.1 from the Releases section of this project and see if that build also has the same bug for you?

**Comment by mycodeitches** [comment]
Hey thanks,

Well it looks to be working now, but I noticed a few problems... probably as it is still prerelease version.. 

Issues noticed.
1. When I save using the alloy framework via Model.save(), I get the following warn/error in the console:
[INFO] :   TiTouchDB: com.obscure.titouchdb.TitouchdbModule@34955741 loaded
[WARN] :   Sync: Error converting lastSequence: null to long.  Using 0
[ERROR] :  ViewProxy: reduce function not recognized: null

2. There are compilation errors but they point to the documentation section. The errors are on HTML tags which have self - closing tags... For example
<a name="module" />

But if I change this to 
<a name="module"></a>

then the error vanishes... is this perhaps an IDE issue? but it was not showing in the earlier version of titouchdb.

Thanks a bunch, but a question... When are are going to release this pre - release version? It looks to be working with version 1.2.0 as well, so I guess I can go with that.

Am not sure which version was downloaded when I used "gittio install" command... 

Thanks a bunch!
